test:
  adapter: test

development:
  adapter: async
  url: wss://express-message-development.onrender.com/cable

production:
  adapter: redis
  url: wss://express-message-production-wp18.onrender.com/cable
  channel_prefix: backend_production