default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: expressmessage
  username: emteam
  password: expressmessage2023
  host: db4free.net  # 使用你在 Render 上部署的 MySQL 主機名稱或 IP 地址
  timezone: "Asia/Taipei"

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: productiondb  # 使用你的 MySQL 正式資料庫名稱
  username: emproduction
  password: expressmessage2023
  host: db4free.net  # 使用你在 Render 上部署的 MySQL 主機名稱或 IP 地址
  timezone: "Asia/Taipei"
