FROM ruby:3.1.2
RUN apt-get update && apt-get install -y cron
RUN mkdir /app
WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID
ENV GOOGLE_CLOUD_KEYFILE_PATH=$GOOGLE_CLOUD_KEYFILE_PATH
RUN bundle install --without test
COPY . /app
RUN rake db:migrate assets:precompile
COPY run_app.sh /app/run_app.sh
RUN chmod +x /app/run_app.sh
CMD ["/app/run_app.sh"]
